export type HealthRecord = {
  month: string;
  facility: "Central Hospital" | "North Clinic" | "South Medical Center";
  department: "General" | "Pediatrics" | "Maternity" | "Respiratory";
  admissions: number;
  outpatient: number;
  bedOccupancy: number;
  waitTime: number;
  respiratory: number;
  malaria: number;
  maternal: number;
  satisfaction: number;
};

export const healthRecords: HealthRecord[] = [
  {
    month: "Jan",
    facility: "Central Hospital",
    department: "General",
    admissions: 180,
    outpatient: 520,
    bedOccupancy: 81,
    waitTime: 48,
    respiratory: 42,
    malaria: 26,
    maternal: 0,
    satisfaction: 87,
  },
  {
    month: "Jan",
    facility: "Central Hospital",
    department: "Respiratory",
    admissions: 92,
    outpatient: 310,
    bedOccupancy: 84,
    waitTime: 44,
    respiratory: 58,
    malaria: 8,
    maternal: 0,
    satisfaction: 84,
  },
  {
    month: "Jan",
    facility: "Central Hospital",
    department: "Pediatrics",
    admissions: 76,
    outpatient: 220,
    bedOccupancy: 70,
    waitTime: 39,
    respiratory: 12,
    malaria: 18,
    maternal: 0,
    satisfaction: 90,
  },
  {
    month: "Jan",
    facility: "Central Hospital",
    department: "Maternity",
    admissions: 72,
    outpatient: 110,
    bedOccupancy: 74,
    waitTime: 35,
    respiratory: 0,
    malaria: 0,
    maternal: 44,
    satisfaction: 91,
  },

  {
    month: "Jan",
    facility: "North Clinic",
    department: "General",
    admissions: 72,
    outpatient: 250,
    bedOccupancy: 62,
    waitTime: 33,
    respiratory: 16,
    malaria: 21,
    maternal: 0,
    satisfaction: 89,
  },
  {
    month: "Jan",
    facility: "North Clinic",
    department: "Respiratory",
    admissions: 36,
    outpatient: 120,
    bedOccupancy: 68,
    waitTime: 31,
    respiratory: 28,
    malaria: 4,
    maternal: 0,
    satisfaction: 85,
  },
  {
    month: "Jan",
    facility: "North Clinic",
    department: "Pediatrics",
    admissions: 34,
    outpatient: 130,
    bedOccupancy: 58,
    waitTime: 28,
    respiratory: 8,
    malaria: 14,
    maternal: 0,
    satisfaction: 91,
  },
  {
    month: "Jan",
    facility: "North Clinic",
    department: "Maternity",
    admissions: 28,
    outpatient: 72,
    bedOccupancy: 55,
    waitTime: 26,
    respiratory: 0,
    malaria: 0,
    maternal: 18,
    satisfaction: 92,
  },

  {
    month: "Jan",
    facility: "South Medical Center",
    department: "General",
    admissions: 108,
    outpatient: 390,
    bedOccupancy: 71,
    waitTime: 38,
    respiratory: 24,
    malaria: 18,
    maternal: 0,
    satisfaction: 88,
  },
  {
    month: "Jan",
    facility: "South Medical Center",
    department: "Respiratory",
    admissions: 46,
    outpatient: 150,
    bedOccupancy: 73,
    waitTime: 36,
    respiratory: 34,
    malaria: 5,
    maternal: 0,
    satisfaction: 83,
  },
  {
    month: "Jan",
    facility: "South Medical Center",
    department: "Pediatrics",
    admissions: 40,
    outpatient: 140,
    bedOccupancy: 63,
    waitTime: 30,
    respiratory: 7,
    malaria: 12,
    maternal: 0,
    satisfaction: 90,
  },
  {
    month: "Jan",
    facility: "South Medical Center",
    department: "Maternity",
    admissions: 38,
    outpatient: 78,
    bedOccupancy: 61,
    waitTime: 27,
    respiratory: 0,
    malaria: 0,
    maternal: 20,
    satisfaction: 91,
  },

  {
    month: "Feb",
    facility: "Central Hospital",
    department: "General",
    admissions: 190,
    outpatient: 550,
    bedOccupancy: 82,
    waitTime: 49,
    respiratory: 46,
    malaria: 28,
    maternal: 0,
    satisfaction: 86,
  },
  {
    month: "Feb",
    facility: "Central Hospital",
    department: "Respiratory",
    admissions: 98,
    outpatient: 325,
    bedOccupancy: 85,
    waitTime: 45,
    respiratory: 63,
    malaria: 9,
    maternal: 0,
    satisfaction: 83,
  },
  {
    month: "Feb",
    facility: "Central Hospital",
    department: "Pediatrics",
    admissions: 80,
    outpatient: 236,
    bedOccupancy: 72,
    waitTime: 40,
    respiratory: 14,
    malaria: 20,
    maternal: 0,
    satisfaction: 89,
  },
  {
    month: "Feb",
    facility: "Central Hospital",
    department: "Maternity",
    admissions: 74,
    outpatient: 116,
    bedOccupancy: 76,
    waitTime: 36,
    respiratory: 0,
    malaria: 0,
    maternal: 47,
    satisfaction: 90,
  },

  {
    month: "Feb",
    facility: "North Clinic",
    department: "General",
    admissions: 76,
    outpatient: 262,
    bedOccupancy: 64,
    waitTime: 34,
    respiratory: 18,
    malaria: 22,
    maternal: 0,
    satisfaction: 88,
  },
  {
    month: "Feb",
    facility: "North Clinic",
    department: "Respiratory",
    admissions: 39,
    outpatient: 126,
    bedOccupancy: 69,
    waitTime: 32,
    respiratory: 31,
    malaria: 4,
    maternal: 0,
    satisfaction: 84,
  },
  {
    month: "Feb",
    facility: "North Clinic",
    department: "Pediatrics",
    admissions: 35,
    outpatient: 136,
    bedOccupancy: 59,
    waitTime: 29,
    respiratory: 9,
    malaria: 15,
    maternal: 0,
    satisfaction: 90,
  },
  {
    month: "Feb",
    facility: "North Clinic",
    department: "Maternity",
    admissions: 29,
    outpatient: 75,
    bedOccupancy: 56,
    waitTime: 27,
    respiratory: 0,
    malaria: 0,
    maternal: 19,
    satisfaction: 91,
  },

  {
    month: "Feb",
    facility: "South Medical Center",
    department: "General",
    admissions: 112,
    outpatient: 402,
    bedOccupancy: 72,
    waitTime: 39,
    respiratory: 26,
    malaria: 18,
    maternal: 0,
    satisfaction: 87,
  },
  {
    month: "Feb",
    facility: "South Medical Center",
    department: "Respiratory",
    admissions: 48,
    outpatient: 154,
    bedOccupancy: 74,
    waitTime: 36,
    respiratory: 37,
    malaria: 5,
    maternal: 0,
    satisfaction: 82,
  },
  {
    month: "Feb",
    facility: "South Medical Center",
    department: "Pediatrics",
    admissions: 42,
    outpatient: 146,
    bedOccupancy: 64,
    waitTime: 31,
    respiratory: 8,
    malaria: 13,
    maternal: 0,
    satisfaction: 89,
  },
  {
    month: "Feb",
    facility: "South Medical Center",
    department: "Maternity",
    admissions: 39,
    outpatient: 81,
    bedOccupancy: 62,
    waitTime: 28,
    respiratory: 0,
    malaria: 0,
    maternal: 21,
    satisfaction: 90,
  },

  {
    month: "Mar",
    facility: "Central Hospital",
    department: "General",
    admissions: 202,
    outpatient: 575,
    bedOccupancy: 84,
    waitTime: 50,
    respiratory: 50,
    malaria: 29,
    maternal: 0,
    satisfaction: 85,
  },
  {
    month: "Mar",
    facility: "Central Hospital",
    department: "Respiratory",
    admissions: 106,
    outpatient: 342,
    bedOccupancy: 87,
    waitTime: 46,
    respiratory: 70,
    malaria: 10,
    maternal: 0,
    satisfaction: 82,
  },
  {
    month: "Mar",
    facility: "Central Hospital",
    department: "Pediatrics",
    admissions: 84,
    outpatient: 248,
    bedOccupancy: 73,
    waitTime: 41,
    respiratory: 15,
    malaria: 21,
    maternal: 0,
    satisfaction: 88,
  },
  {
    month: "Mar",
    facility: "Central Hospital",
    department: "Maternity",
    admissions: 78,
    outpatient: 120,
    bedOccupancy: 78,
    waitTime: 37,
    respiratory: 0,
    malaria: 0,
    maternal: 50,
    satisfaction: 89,
  },

  {
    month: "Mar",
    facility: "North Clinic",
    department: "General",
    admissions: 80,
    outpatient: 275,
    bedOccupancy: 66,
    waitTime: 35,
    respiratory: 19,
    malaria: 23,
    maternal: 0,
    satisfaction: 87,
  },
  {
    month: "Mar",
    facility: "North Clinic",
    department: "Respiratory",
    admissions: 42,
    outpatient: 132,
    bedOccupancy: 71,
    waitTime: 33,
    respiratory: 34,
    malaria: 5,
    maternal: 0,
    satisfaction: 83,
  },
  {
    month: "Mar",
    facility: "North Clinic",
    department: "Pediatrics",
    admissions: 37,
    outpatient: 142,
    bedOccupancy: 60,
    waitTime: 30,
    respiratory: 10,
    malaria: 16,
    maternal: 0,
    satisfaction: 89,
  },
  {
    month: "Mar",
    facility: "North Clinic",
    department: "Maternity",
    admissions: 30,
    outpatient: 77,
    bedOccupancy: 57,
    waitTime: 28,
    respiratory: 0,
    malaria: 0,
    maternal: 20,
    satisfaction: 90,
  },

  {
    month: "Mar",
    facility: "South Medical Center",
    department: "General",
    admissions: 118,
    outpatient: 418,
    bedOccupancy: 74,
    waitTime: 40,
    respiratory: 28,
    malaria: 19,
    maternal: 0,
    satisfaction: 86,
  },
  {
    month: "Mar",
    facility: "South Medical Center",
    department: "Respiratory",
    admissions: 51,
    outpatient: 160,
    bedOccupancy: 76,
    waitTime: 37,
    respiratory: 40,
    malaria: 6,
    maternal: 0,
    satisfaction: 81,
  },
  {
    month: "Mar",
    facility: "South Medical Center",
    department: "Pediatrics",
    admissions: 44,
    outpatient: 152,
    bedOccupancy: 65,
    waitTime: 32,
    respiratory: 8,
    malaria: 13,
    maternal: 0,
    satisfaction: 88,
  },
  {
    month: "Mar",
    facility: "South Medical Center",
    department: "Maternity",
    admissions: 40,
    outpatient: 83,
    bedOccupancy: 63,
    waitTime: 29,
    respiratory: 0,
    malaria: 0,
    maternal: 22,
    satisfaction: 89,
  },

  {
    month: "Apr",
    facility: "Central Hospital",
    department: "General",
    admissions: 208,
    outpatient: 595,
    bedOccupancy: 85,
    waitTime: 50,
    respiratory: 52,
    malaria: 26,
    maternal: 0,
    satisfaction: 85,
  },
  {
    month: "Apr",
    facility: "Central Hospital",
    department: "Respiratory",
    admissions: 109,
    outpatient: 350,
    bedOccupancy: 88,
    waitTime: 47,
    respiratory: 74,
    malaria: 9,
    maternal: 0,
    satisfaction: 81,
  },
  {
    month: "Apr",
    facility: "Central Hospital",
    department: "Pediatrics",
    admissions: 86,
    outpatient: 255,
    bedOccupancy: 74,
    waitTime: 42,
    respiratory: 16,
    malaria: 18,
    maternal: 0,
    satisfaction: 88,
  },
  {
    month: "Apr",
    facility: "Central Hospital",
    department: "Maternity",
    admissions: 80,
    outpatient: 122,
    bedOccupancy: 79,
    waitTime: 37,
    respiratory: 0,
    malaria: 0,
    maternal: 52,
    satisfaction: 88,
  },

  {
    month: "Apr",
    facility: "North Clinic",
    department: "General",
    admissions: 82,
    outpatient: 281,
    bedOccupancy: 67,
    waitTime: 35,
    respiratory: 18,
    malaria: 21,
    maternal: 0,
    satisfaction: 87,
  },
  {
    month: "Apr",
    facility: "North Clinic",
    department: "Respiratory",
    admissions: 43,
    outpatient: 136,
    bedOccupancy: 72,
    waitTime: 33,
    respiratory: 36,
    malaria: 5,
    maternal: 0,
    satisfaction: 83,
  },
  {
    month: "Apr",
    facility: "North Clinic",
    department: "Pediatrics",
    admissions: 38,
    outpatient: 145,
    bedOccupancy: 61,
    waitTime: 31,
    respiratory: 9,
    malaria: 15,
    maternal: 0,
    satisfaction: 89,
  },
  {
    month: "Apr",
    facility: "North Clinic",
    department: "Maternity",
    admissions: 31,
    outpatient: 79,
    bedOccupancy: 58,
    waitTime: 29,
    respiratory: 0,
    malaria: 0,
    maternal: 21,
    satisfaction: 90,
  },

  {
    month: "Apr",
    facility: "South Medical Center",
    department: "General",
    admissions: 122,
    outpatient: 430,
    bedOccupancy: 75,
    waitTime: 41,
    respiratory: 29,
    malaria: 17,
    maternal: 0,
    satisfaction: 86,
  },
  {
    month: "Apr",
    facility: "South Medical Center",
    department: "Respiratory",
    admissions: 54,
    outpatient: 166,
    bedOccupancy: 77,
    waitTime: 38,
    respiratory: 43,
    malaria: 5,
    maternal: 0,
    satisfaction: 80,
  },
  {
    month: "Apr",
    facility: "South Medical Center",
    department: "Pediatrics",
    admissions: 45,
    outpatient: 157,
    bedOccupancy: 66,
    waitTime: 32,
    respiratory: 8,
    malaria: 12,
    maternal: 0,
    satisfaction: 88,
  },
  {
    month: "Apr",
    facility: "South Medical Center",
    department: "Maternity",
    admissions: 42,
    outpatient: 85,
    bedOccupancy: 64,
    waitTime: 29,
    respiratory: 0,
    malaria: 0,
    maternal: 23,
    satisfaction: 89,
  },

  {
    month: "May",
    facility: "Central Hospital",
    department: "General",
    admissions: 218,
    outpatient: 620,
    bedOccupancy: 86,
    waitTime: 51,
    respiratory: 55,
    malaria: 27,
    maternal: 0,
    satisfaction: 84,
  },
  {
    month: "May",
    facility: "Central Hospital",
    department: "Respiratory",
    admissions: 115,
    outpatient: 364,
    bedOccupancy: 89,
    waitTime: 48,
    respiratory: 79,
    malaria: 9,
    maternal: 0,
    satisfaction: 80,
  },
  {
    month: "May",
    facility: "Central Hospital",
    department: "Pediatrics",
    admissions: 90,
    outpatient: 264,
    bedOccupancy: 75,
    waitTime: 42,
    respiratory: 17,
    malaria: 19,
    maternal: 0,
    satisfaction: 87,
  },
  {
    month: "May",
    facility: "Central Hospital",
    department: "Maternity",
    admissions: 82,
    outpatient: 126,
    bedOccupancy: 80,
    waitTime: 38,
    respiratory: 0,
    malaria: 0,
    maternal: 54,
    satisfaction: 88,
  },

  {
    month: "May",
    facility: "North Clinic",
    department: "General",
    admissions: 84,
    outpatient: 288,
    bedOccupancy: 68,
    waitTime: 36,
    respiratory: 19,
    malaria: 20,
    maternal: 0,
    satisfaction: 86,
  },
  {
    month: "May",
    facility: "North Clinic",
    department: "Respiratory",
    admissions: 45,
    outpatient: 140,
    bedOccupancy: 73,
    waitTime: 34,
    respiratory: 38,
    malaria: 5,
    maternal: 0,
    satisfaction: 82,
  },
  {
    month: "May",
    facility: "North Clinic",
    department: "Pediatrics",
    admissions: 39,
    outpatient: 150,
    bedOccupancy: 62,
    waitTime: 31,
    respiratory: 9,
    malaria: 15,
    maternal: 0,
    satisfaction: 88,
  },
  {
    month: "May",
    facility: "North Clinic",
    department: "Maternity",
    admissions: 32,
    outpatient: 81,
    bedOccupancy: 59,
    waitTime: 29,
    respiratory: 0,
    malaria: 0,
    maternal: 22,
    satisfaction: 89,
  },

  {
    month: "May",
    facility: "South Medical Center",
    department: "General",
    admissions: 128,
    outpatient: 444,
    bedOccupancy: 77,
    waitTime: 42,
    respiratory: 30,
    malaria: 18,
    maternal: 0,
    satisfaction: 85,
  },
  {
    month: "May",
    facility: "South Medical Center",
    department: "Respiratory",
    admissions: 56,
    outpatient: 171,
    bedOccupancy: 79,
    waitTime: 39,
    respiratory: 46,
    malaria: 6,
    maternal: 0,
    satisfaction: 80,
  },
  {
    month: "May",
    facility: "South Medical Center",
    department: "Pediatrics",
    admissions: 47,
    outpatient: 162,
    bedOccupancy: 67,
    waitTime: 33,
    respiratory: 8,
    malaria: 12,
    maternal: 0,
    satisfaction: 87,
  },
  {
    month: "May",
    facility: "South Medical Center",
    department: "Maternity",
    admissions: 43,
    outpatient: 87,
    bedOccupancy: 65,
    waitTime: 30,
    respiratory: 0,
    malaria: 0,
    maternal: 24,
    satisfaction: 88,
  },

  {
    month: "Jun",
    facility: "Central Hospital",
    department: "General",
    admissions: 226,
    outpatient: 642,
    bedOccupancy: 87,
    waitTime: 52,
    respiratory: 58,
    malaria: 28,
    maternal: 0,
    satisfaction: 83,
  },
  {
    month: "Jun",
    facility: "Central Hospital",
    department: "Respiratory",
    admissions: 121,
    outpatient: 378,
    bedOccupancy: 90,
    waitTime: 49,
    respiratory: 84,
    malaria: 10,
    maternal: 0,
    satisfaction: 79,
  },
  {
    month: "Jun",
    facility: "Central Hospital",
    department: "Pediatrics",
    admissions: 93,
    outpatient: 272,
    bedOccupancy: 76,
    waitTime: 43,
    respiratory: 18,
    malaria: 20,
    maternal: 0,
    satisfaction: 87,
  },
  {
    month: "Jun",
    facility: "Central Hospital",
    department: "Maternity",
    admissions: 84,
    outpatient: 130,
    bedOccupancy: 81,
    waitTime: 38,
    respiratory: 0,
    malaria: 0,
    maternal: 56,
    satisfaction: 87,
  },

  {
    month: "Jun",
    facility: "North Clinic",
    department: "General",
    admissions: 86,
    outpatient: 295,
    bedOccupancy: 69,
    waitTime: 36,
    respiratory: 20,
    malaria: 20,
    maternal: 0,
    satisfaction: 85,
  },
  {
    month: "Jun",
    facility: "North Clinic",
    department: "Respiratory",
    admissions: 46,
    outpatient: 144,
    bedOccupancy: 74,
    waitTime: 34,
    respiratory: 40,
    malaria: 5,
    maternal: 0,
    satisfaction: 81,
  },
  {
    month: "Jun",
    facility: "North Clinic",
    department: "Pediatrics",
    admissions: 40,
    outpatient: 154,
    bedOccupancy: 63,
    waitTime: 32,
    respiratory: 10,
    malaria: 16,
    maternal: 0,
    satisfaction: 88,
  },
  {
    month: "Jun",
    facility: "North Clinic",
    department: "Maternity",
    admissions: 33,
    outpatient: 83,
    bedOccupancy: 60,
    waitTime: 30,
    respiratory: 0,
    malaria: 0,
    maternal: 23,
    satisfaction: 89,
  },

  {
    month: "Jun",
    facility: "South Medical Center",
    department: "General",
    admissions: 132,
    outpatient: 458,
    bedOccupancy: 78,
    waitTime: 43,
    respiratory: 32,
    malaria: 18,
    maternal: 0,
    satisfaction: 84,
  },
  {
    month: "Jun",
    facility: "South Medical Center",
    department: "Respiratory",
    admissions: 58,
    outpatient: 176,
    bedOccupancy: 80,
    waitTime: 39,
    respiratory: 49,
    malaria: 6,
    maternal: 0,
    satisfaction: 79,
  },
  {
    month: "Jun",
    facility: "South Medical Center",
    department: "Pediatrics",
    admissions: 48,
    outpatient: 168,
    bedOccupancy: 68,
    waitTime: 33,
    respiratory: 9,
    malaria: 13,
    maternal: 0,
    satisfaction: 87,
  },
  {
    month: "Jun",
    facility: "South Medical Center",
    department: "Maternity",
    admissions: 44,
    outpatient: 90,
    bedOccupancy: 66,
    waitTime: 30,
    respiratory: 0,
    malaria: 0,
    maternal: 25,
    satisfaction: 88,
  },
];